# -*- coding: utf-8 -*-

"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

import re
from setuptools import setup

NAME = 'Manami'
ICON = 'appbundle/app.icns'
VERSION = '1.0.0'
INFO = 'Manami - Simple Game Skeleton for Go/SDL2'
COPYRIGHT = '© 2015 CreepyPanda Software'
IDENTIFIER = 'com.creepypanda.games.manami'

PLIST = {'CFBundleName': NAME,
         'CFBundleIconFile': ICON,
         'CFBundleVersion': VERSION,
         'CFBundleExecutable': NAME,
         'CFBundleGetInfoString': INFO,
         'CFBundleIdentifier': IDENTIFIER,
         'CFBundleShortVersionString': re.search(r'\d+\.\d+', VERSION).group(0),
         'NSHumanReadableCopyright': COPYRIGHT}

APP = ['dummy.py']

FRAMEWORKS = ['/Library/Frameworks/SDL2.framework',
              '/Library/Frameworks/SDL2_ttf.framework',
              '/Library/Frameworks/SDL2_image.framework',
              '/Library/Frameworks/SDL2_mixer.framework']

OPTIONS = {'frameworks': FRAMEWORKS,
           'iconfile': ICON,
           'plist': PLIST}

setup(
    app=APP,
    options={'py2app': OPTIONS},
    setup_requires=['py2app']
)
