# -*- coding: utf-8 -*-

"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

import re
from setuptools import setup

NAME = 'Manami'
ICON = 'bundle_res/App.icns'
VERSION = '1.0.0'
INFO = 'Manami - Simple Game Skeleton for Go/SFML2'
COPYRIGHT = '© 2015 CreepyPanda Software'
IDENTIFIER = 'com.creepypanda.games.manami'

PLIST = {'CFBundleName': NAME,
         'CFBundleIconFile': ICON,
         'CFBundleVersion': VERSION,
         'CFBundleExecutable': NAME,
         'CFBundleGetInfoString': INFO,
         'CFBundleIdentifier': IDENTIFIER,
         'CFBundleShortVersionString': re.search(r'\d+\.\d+', VERSION).group(0),
         'NSHumanReadableCopyright': COPYRIGHT}

APP = ['dummy.py']

FRAMEWORKS = ['/usr/local/opt/csfml/lib/libcsfml-window.2.3.dylib',
              '/usr/local/opt/csfml/lib/libcsfml-graphics.2.3.dylib',
              '/usr/local/opt/csfml/lib/libcsfml-audio.2.3.dylib',
              '/usr/local/opt/csfml/lib/libcsfml-system.2.3.dylib']

OPTIONS = {'frameworks': FRAMEWORKS,
           'iconfile': ICON,
           'plist': PLIST}

setup(
    app=APP,
    options={'py2app': OPTIONS},
    setup_requires=['py2app']
)
